---
title: "R Notebook"
author: "Sreeja Nair"
output: html_notebook
---


```{r , include = FALSE}

library(tidyverse)

?mtcars

```


```{r setup, echo=FALSE}

cars <- read_csv("C:/Users/sreej/Desktop/Sorenson/Training/cars.csv")

names(cars)  #column headings

cars %>% 
  count(cyl)

cyltable <- cars %>% 
  count(cyl) %>% 
  print()

cars %>% 
  count(cyl, gear)

cars %>% 
  summarise(meanmpg = mean(mpg, na.rm = T))

cars %>% 
  group_by(cyl) %>% 
  summarise(meanmpg = mean(mpg, na.rm =T))

cars %>% 
  count(cyl) %>% 
  ggplot(aes(x=cyl, y=n))+
  geom_col()

cars %>% 
  count(cyl) %>%
  ggplot(aes(x=cyl, y=n))+
  geom_abline()



cars %>% 
  count(cyl) %>% 
  ggplot(aes(x=cyl, y=n))+
  geom_col(fill="#741D5A")+
  labs(y="Number", x= "Cylinders")+
  ggtitle("Number of Cars by Cylinder")+
  theme_minimal()


```


# Exercises

```{r}

# Create table of the number of cars by gear 

geartable <- cars %>% 
  count(gear) %>% 
  print()



# Create table of the number of cars by carb

carbtable <- cars %>% 
  count(carb) %>% 
  print()

#	Create a table of vs (0 - V shaped engine, 1 - Staight engine)

vstable <- cars %>% 
  count(vs) %>% 
  print()

#	Create a table of am (0 - Auto transmission, 1 - Manual transmission)

amtable <- cars %>% 
  count(am) %>% 
  print()

#	Create a table of cyl by gear

cylbygear <- cars %>%
  count(cyl, gear) %>% 
  print()
  
#	Create a table of cyl by am 

cylbyam <- cars %>% 
  count(cyl,am) %>% 
  print()
  
#	Create a table of cyl by vs

cylbyvs <- cars %>%  
  count(cyl,vs) %>% 
  print()

#	Create a histogram of wt

?geom_histogram

summary(cars)

cars %>%  
  ggplot(aes(x=wt))+
  geom_histogram(binwidth = 0.2, fill= "#CD5C5C")+
  ggtitle("Number of Cars by Weight")+
  theme_minimal()
  


#	Create a histogram of mpg

cars %>%  
  ggplot(aes(x=mpg))+
  geom_histogram(binwidth = 3, fill= "#CD5C5C")+
  ggtitle("Number of Cars by Miles per Gallon")+
  theme_minimal()


#	Create a histogram of qsec
summary(cars$qsec)
 
cars %>% 
  ggplot(aes(x=qsec))+
  geom_histogram(binwidth = 0.5, fill="#CD5C5C")+
  ggtitle("Number of cars by 1/4 mile time")+
  theme_minimal()


#	Create a histogram of hp 

summary(cars$hp)

cars %>% 
  ggplot(aes(x=hp))+
  geom_histogram(binwidth = 25, fill = "#CD5C5C")+
  ggtitle("Numberof cars by horsepower")+
  theme_minimal()


#	Create a table of mean mpg by cyl

mpgbycyl <- cars %>% 
  group_by(cyl) %>% 
  summarise(meanmpg = mean(mpg, na.rm = T)) %>% 
  print()


#	Graph mean mpg by cyl 

mpgbycyl %>% 
  ggplot(aes(x = cyl, y = meanmpg))+
  geom_point(color = "#CD5C5C", size =3)+
  labs(title = "Mean mpg by cylinder", x= "No. of cylinders", y="Mean miles per gallon")


#	Create a table of mean wt by cyl

wtbycyl <- cars %>% 
  group_by(cyl) %>% 
  summarise(meanwt = mean(wt, na.rm = T)) %>% 
  print()


#	Graph mean wt by cyl

wtbycyl %>% 
  ggplot(aes(x = cyl, y = meanwt))+
  geom_point(color = "#CD5C5C", size =3)+
  labs(title = "Mean wt. by cylinder", x= "No. of cylinders", y="Mean weight")


#	Create a table of mean hp by cyl

hpbycyl <- cars %>% 
  group_by(cyl) %>% 
  summarise(meanhp = mean(hp,na.rm = T)) %>% 
  print()


#	Graph mean hp by cyl

hpbycyl %>% 
  ggplot(aes(x = cyl, y=meanhp))+
  geom_point(color = "#CD5C5C", size =3)+
  labs(title = "Mean horsepower by cylinder", x = "No. of cylinders", y="Mean horsepower")


#	Do any other exploratory analysis that interests you  

#mean mpg by carb

mpgbycarb <- cars %>% 
  group_by(carb) %>% 
  summarise(meanmpg = mean(mpg, na.rm = T)) %>% 
  print() #More the number of carburetors, lesser the mpg  


cars %>% 
  group_by(carb,cyl) %>% 
  summarise(meanmpg = mean(mpg, na.rm = T)) %>% 
  print() # For a given number of carburetor, as the number of cylinders increase, mpg decreases



```

